n---
title: "ML_images"
output: html_document
date: '2022-05-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Importing Necessary Libraries for the Code
suppressPackageStartupMessages(suppressWarnings(library(ggplot2)))
suppressPackageStartupMessages(suppressWarnings(library(tidyverse)))
suppressPackageStartupMessages(suppressWarnings(library(patchwork)))
suppressPackageStartupMessages(suppressWarnings(library(RColorBrewer)))
suppressPackageStartupMessages(suppressWarnings(library(pheatmap)))
suppressPackageStartupMessages(suppressWarnings(library(ggpmisc)))
suppressPackageStartupMessages(suppressWarnings(library(reshape2)))
```

```{r}
#MetaSUB Files Import
metasub_metadata <- read.csv("csv_files/updated_metadata.csv")
cv_comp <- read.csv("csv_files/cv_comparison.csv", header=T, row.names="Feature_Name")
metasub_species <- t(read.csv("csv_files/metasub_species.csv", header=T))
metasub_species <- data.frame(metasub_species[-1, ])
metapred_city <- read.csv("csv_files/output_metrics_city.csv")
city_noise <- read.csv("csv_files/noise_city.csv")
metapred_cont <- read.csv("csv_files/output_metrics_continent.csv")

#cassandra_output
cassandra_cities <- t(read.csv("csv_files/cassandra_cities.csv", header=T))
cassandra_cities_mp <- t(read.csv("csv_files/cass_mp_city.csv", header=T))
cassandra_cont <- t(read.csv("csv_files/cassandra_continent.csv", header=T))
cassandra_cont_mp <- t(read.csv("csv_files/cass_mp_cont.csv", header=T))


#Tara Files Import
tara_taxa <- read.csv("csv_files/tara_taxa_all.csv")
#tara_otu <- read.csv("csv_files/tara_otu_accuracy.csv")
```

```{r}
#city precision/recall
city_meta <- metapred_city[metapred_city$Noise==0,]
ggplot(data=city_meta, aes(y=Precision, x=Recall, color=Classifier, shape=Preprocessing)) + geom_point(size=2)  + 
  labs(title="Precision vs Recall for MetaSUB City") + theme(legend.title = element_text(size=7), legend.text = element_text(size=7))
```

```{r}
ggplot(data=city_meta, aes(x=Accuracy, y=Training_Time_in_sec, color=Classifier, fill=Classifier)) +
geom_point(size=2)  + stat_ellipse() + 
  labs(title="Accuracy vs Training Time for MetaSUB City")
```
```{r}
ggplot(data=city_noise, aes(x=log(Noise), y=Accuracy, color=Classifier, linetype=Preprocessing, shape=Preprocessing)) +geom_line()+
  geom_point()  +
  labs(title="Effect of Gaussian Noise (Model Stability) for the best model") +
  theme(legend.title = element_text(size=7))
```
```{r}
#cont precision/recall
cont_meta <- metapred_city[metapred_cont$Noise==0,]
ggplot(data=cont_meta, aes(y=Precision, x=Recall, color=Classifier, shape=Preprocessing)) + geom_point(size=2)  + 
  labs(title="Precision vs Recall for MetaSUB Continent") + theme(legend.title = element_text(size=7), legend.text = element_text(size=7))
```



```{r}
#data interpolation
pheatmap(cv_comp,gaps_col=3, cluster_rows=FALSE, cluster_cols=FALSE, main = "Cross-validation for data Interpolation") 
```

```{r}
#city
city_species <- rownames(cassandra_cities)
cont_species <- rownames(cassandra_cont)

metasub_species[is.na(metasub_species)] <- 0
metasub_species2 <- data.frame(metasub_species)
metasub_species2 <- data.frame(apply(metasub_species2, 2, function(x) as.numeric(as.character(x))))
metasub_species2 <- sweep(metasub_species2, 2, colSums(metasub_species2), `/`)

species_metric <- data.frame(matrix(ncol = 3, nrow = 3757))
colnames(species_metric) <- c('species', 'species_abundance', 'species_prevalance')
species_metric$species <- rownames(metasub_species)
species_metric$species_abundance <- rowMeans(metasub_species2)
species_metric$species_prevalance <- rowSums(metasub_species != 0 )

feature_importance <- rowMeans(cassandra_cities_mp)
DF <- as.data.frame(feature_importance)
DF$species <- rownames(DF)
data_frame_merge <- merge(species_metric, DF, by = 'species', all = F)
```

```{r}
ggplot(data_frame_merge, aes(x= -log(species_abundance), y= -log(species_prevalance))) + 
  geom_point() +
  stat_poly_line() +
  stat_poly_eq() 
```

```{r}
ggplot(data_frame_merge, aes(x= -log(species_abundance), y= -log(feature_importance))) + 
  geom_point() +
  stat_poly_line() +
  stat_poly_eq() 
```


```{r}
ggplot(data_frame_merge, aes(x= -log(species_prevalance), y= -log(feature_importance))) + 
  geom_point() +
  stat_poly_line() +
  stat_poly_eq() 
```

```{r}
rownames(metasub_species2) <- rownames(metasub_species)
metasub_species2$species <- rownames(metasub_species)
city_abun <- metasub_species2[metasub_species2$species %in% city_species, ]
city_abun <- data.frame(species = row.names(city_abun), city_abun)
city <- melt(city_abun, id.var = 'species', na.rm = TRUE)
city$variable = NULL
city <- city[city$value!=0,]
city$value <- as.numeric(city$value)
ggplot(city, aes(x=species, y=-log(value), fill=species)) +
  geom_boxplot(outlier.shape = NA) + theme(axis.text.x = element_text(angle = 90), legend.position="none")
```

```{r}
cont_abun <- metasub_species2[metasub_species2$species %in% cont_species, ]
cont_abun <- data.frame(species = row.names(cont_abun), cont_abun)
cont <- melt(cont_abun, id.var = 'species', na.rm = TRUE)
cont$value <- as.numeric(cont$value)
cont <- cont[cont$value!=0,]
ggplot(cont, aes(x=species, y=-log(value), fill=species)) +
  geom_boxplot(outlier.shape = NA) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position="none")
```




```{r}
#Tara Validation
tara <- tara_taxa[tara_taxa$Noise==0,]
ggplot(data=tara, aes(y=Accuracy, x=-log(Training_Time_in_sec), color=Taxonomic_classification, shape=Name)) +
  geom_point(size=4)  + 
  scale_color_manual(values=c("royalblue1", "coral1", "darkolivegreen", "darkorchid", "deeppink", "goldenrod1")) +
  labs(title="Model Accuracy vs Time Taken for model Training on given TARA Taxonomic Classification")
```

```{r}
ggplot(data=tara, aes(x=Precision, y=Recall, color=Taxonomic_classification, shape=Name)) +
  geom_point(size=4) +
  scale_color_manual(values=c("royalblue1", "coral1", "darkolivegreen", "darkorchid", "deeppink", "goldenrod1"))+
  labs(title="Model Precision and Recall on given TARA Taxonomic Classification")
```

```{r}
ggplot(data=tara_taxa, aes(x=log(Noise), y=Accuracy, color=Taxonomic_classification, linetype=Name, shape=Name)) +
  geom_line()+
  geom_point() + 
  scale_color_manual(values=c("royalblue1", "coral1", "darkolivegreen", "darkorchid", "deeppink", "goldenrod1")) +
  labs(title="Effect of Gaussian Noise (Model Stability) for the best model prediction")
```

```{}
ggplot(data=tara_otu, aes(x=log(noise), y=accuracy, color=name, shape=name)) +
  geom_line() + 
  geom_point() + 
  scale_color_manual(values=c("royalblue1", "coral1", "darkolivegreen", "darkorchid", "goldenrod1"))+
  labs(title="Effect of Gaussian Noise (Model Stability) for predicting OTU at similar accuracy")
```













